name: Build macOS universal binary
on:
  workflow_call:
    inputs:
      production:
        type: boolean
        description: "Run in production mode"
        required: true
      version:
        type: string
        description: "Version (without leading \"v\")"
      year:
        type: string
        description: "Copyright year"
jobs:
  build-macos-amd64:
    name: Build macOS Intel binary
    uses: ghifari160/migrate/.github/workflows/build-macos.yaml@main
    with:
      goarch: amd64
      archid: amd64
      production: ${{inputs.production}}
      version: ${{inputs.version}}
      year: ${{inputs.year}}
  build-macos-arm64:
    name: Build macOS Apple Silicon binary
    uses: ghifari160/migrate/.github/workflows/build-macos.yaml@main
    with:
      goarch: arm64
      archid: arm64
      production: ${{inputs.production}}
      version: ${{inputs.version}}
      year: ${{inputs.year}}
  build-macos:
    name: Build macOS universal binary
    needs: [build-macos-amd64, build-macos-arm64]
    runs-on: macos-12
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      id: artifacts
      with:
        path: migrate
    - name: Adjust artifacts permissions
      run: |
        chmod a+x ${{steps.artifacts.outputs.download-path}}/migrate-macos_amd64/migrate
        chmod a+x ${{steps.artifacts.outputs.download-path}}/migrate-macos_arm64/migrate
    - name: Prepare build directory
      run: mkdir macos
    - name: Build macOS universal binary
      run: lipo ${{steps.artifacts.outputs.download-path}}/migrate-macos_amd64/migrate ${{steps.artifacts.outputs.download-path}}/migrate-macos_arm64/migrate -create -output macos/migrate
    - name: Create tarball
      run: cd macos && tar -zcvf ../migrate-macos.tar.gz . && cd ..
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: migrate-macos.tar.gz
        path: migrate-macos.tar.gz
