name: Build Windows binary
on:
  workflow_call:
    inputs:
      goarch:
        type: string
        required: true
        description: "GOARCH"
      archid:
        type: string
        required: true
        description: "Arch ID"
      production:
        type: boolean
        description: "Run in production mode"
      version:
        type: string
        description: "Version (without leading \"v\")"
      year:
        type: string
        description: "Copyright year"
jobs:
  build-windows:
    name: Build Windows binary
    runs-on: ubuntu-latest
    steps:
    - name: Setup source repo
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: "^1.19.3"
    - name: Run prerelease script
      if: ${{inputs.production}}
      run: |
        go run ./scripts/prerelease -noninteractive \
          -ver ${{inputs.version}} -copyyear ${{inputs.year}}
    - name: Build Windows binary (${{inputs.archid}})
      if: ${{!inputs.production}}
      run: GOOS=windows GOARCH=${{inputs.goarch}} go build -o out/migrate main.go
    - name: Build Windows RELEASE binary (${{inputs.archid}})
      if: ${{inputs.production}}
      run: GOOS=windows GOARCH=${{inputs.goarch}} go build -tags prod -o out/migrate main.go
    - name: Create tarball
      run: cd out && tar -zcvf ../migrate-windows_${{inputs.archid}}.tar.gz . && cd ..
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: migrate-windows_${{inputs.archid}}.tar.gz
        path: migrate-windows_${{inputs.archid}}.tar.gz
